# -*- coding: utf-8 -*-
"""
asteroids.py — real asteroid positions + conjunctions to the natal chart.

Replaces the old client-side page, whose positions were generated by a
pseudo-random hash of the asteroid number and were not astronomical.

Swiss Ephemeris computes each asteroid from its own data file:
  * Ceres, Pallas, Juno, Vesta      -> seas_18.se1   (already in ephe/)
  * Chiron, Pholus                  -> seas_18.se1   (already in ephe/)
  * every other numbered asteroid   -> se#####s.se1  (must be added)

Asteroids whose file is missing are reported in `unavailable` with the
exact filename needed, so nothing is ever invented.
"""

import math
import os
import urllib.request
import urllib.parse
import swisseph as swe

# Where the ephemeris lives (set by app.py; falls back to ./ephe)
EPHE_DIR = os.environ.get('SE_EPHE_PATH') or os.path.join(
    os.path.dirname(os.path.abspath(__file__)), 'ephe')

# Astrodienst mirrors, tried in order. The backend downloads an
# asteroid's file the first time it is requested and caches it in
# ephe/astN/, so no files have to be committed to the repo.
FILE_SOURCES = [
    'https://www.astro.com/ftp/swisseph/ephe/{folder}{file}',
    'https://www.astro.com/ftp/swisseph/ephe/asteroids/{folder}{file}',
    'https://raw.githubusercontent.com/aloistr/swisseph/master/ephe/{folder}{file}',
]
_TRIED = set()
LAST_ERRORS = []          # why downloads failed (see /api/asteroids/diag)


def ensure_file(num):
    """Fetch this asteroid's Swiss Ephemeris file if we don't have it.

    Returns True when the file is present afterwards. Failures are
    remembered so a missing asteroid is only attempted once per process.
    """
    fn, folder = _file_for(num)
    if folder.startswith('ephe/'):
        folder = folder[5:]
    dest_dir = os.path.join(EPHE_DIR, folder) if folder else EPHE_DIR
    dest = os.path.join(dest_dir, fn)
    if os.path.exists(dest) and os.path.getsize(dest) > 1000:
        return True
    if num in _TRIED:
        return False
    _TRIED.add(num)
    try:
        os.makedirs(dest_dir, exist_ok=True)
    except Exception:
        return False
    for tpl in FILE_SOURCES:
        url = tpl.format(folder=folder, file=fn)
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'magnus-astro/1.0'})
            with urllib.request.urlopen(req, timeout=25) as r:
                data = r.read()
            if len(data) < 1000:          # not a real ephemeris file
                LAST_ERRORS.append('%s -> only %d bytes' % (url, len(data)))
                continue
            with open(dest, 'wb') as f:
                f.write(data)
            swe.set_ephe_path(EPHE_DIR)   # re-scan so the new file is seen
            return True
        except Exception as e:
            LAST_ERRORS.append('%s -> %s' % (url, e))
            continue
    return False


# ---------------------------------------------------------------
# FILE-FREE FALLBACK: NASA/JPL Horizons
# Astrodienst may refuse downloads from cloud IPs (the same problem
# app.py documents for the geocoders). Horizons serves positions over
# a plain HTTPS API and needs no local files at all.
# ---------------------------------------------------------------
HORIZONS = 'https://ssd.jpl.nasa.gov/api/horizons.api'
_HZ_CACHE = {}


def horizons_lonlat(num, jd):
    """Geocentric ecliptic longitude/latitude of asteroid `num` at jd."""
    key = (num, round(jd, 5))
    if key in _HZ_CACHE:
        return _HZ_CACHE[key]
    q = {
        'format': 'text',
        'COMMAND': "'%d;'" % num,        # ';' = small-body lookup by number
        'OBJ_DATA': 'NO',
        'MAKE_EPHEM': 'YES',
        'EPHEM_TYPE': 'OBSERVER',
        'CENTER': "'500@399'",           # geocentric
        'QUANTITIES': "'31'",            # observer ecliptic lon & lat
        'TLIST': '%.6f' % jd,
        'CSV_FORMAT': 'YES',
    }
    url = HORIZONS + '?' + urllib.parse.urlencode(q)
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'magnus-astro/1.0'})
        with urllib.request.urlopen(req, timeout=30) as r:
            txt = r.read().decode('utf-8', 'replace')
    except Exception as e:
        LAST_ERRORS.append('horizons %d -> %s' % (num, e))
        return None
    if '$$SOE' not in txt:
        LAST_ERRORS.append('horizons %d -> no ephemeris block' % num)
        return None
    body = txt.split('$$SOE', 1)[1].split('$$EOE', 1)[0].strip()
    line = body.splitlines()[0] if body.splitlines() else ''
    parts = [p.strip() for p in line.split(',')]
    nums = []
    for p in parts:
        try:
            nums.append(float(p))
        except ValueError:
            pass
    if len(nums) < 2:
        LAST_ERRORS.append('horizons %d -> unparsed: %s' % (num, line[:80]))
        return None
    lon, lat = nums[-2], nums[-1]
    _HZ_CACHE[key] = (lon % 360.0, lat)
    return _HZ_CACHE[key]

SIGNS_KA = ['ვერძი', 'კურო', 'ტყუპები', 'კირჩხიბი', 'ლომი', 'ქალწული',
            'სასწორი', 'მორიელი', 'მშვილდოსანი', 'თხის რქა',
            'მერწყული', 'თევზები']
ELEMENT_KA = ['ცეცხლი', 'მიწა', 'ჰაერი', 'წყალი']

# asteroids that live in the main-file set
SPECIAL = {1: swe.CERES, 2: swe.PALLAS, 3: swe.JUNO, 4: swe.VESTA,
           2060: swe.CHIRON, 5145: swe.PHOLUS}

# natal bodies asteroids are checked against
NATAL = [('მზე', swe.SUN), ('მთვარე', swe.MOON), ('მერკური', swe.MERCURY),
         ('ვენერა', swe.VENUS), ('მარსი', swe.MARS), ('იუპიტერი', swe.JUPITER),
         ('სატურნი', swe.SATURN), ('ურანი', swe.URANUS),
         ('ნეპტუნი', swe.NEPTUNE), ('პლუტონი', swe.PLUTO)]

ASPECTS = [(0.0, 'შეერთება', '☌'), (180.0, 'ოპოზიცია', '☍'),
           (120.0, 'ტრინი', '△'), (90.0, 'კვადრატი', '□'),
           (60.0, 'სექსტილი', '⚹')]


def _house(deg, cusps):
    for i in range(12):
        a, b = cusps[i], cusps[(i + 1) % 12]
        if a <= b:
            if a <= deg < b:
                return i + 1
        else:
            if deg >= a or deg < b:
                return i + 1
    return 1


def _sep(a, b):
    d = abs((a - b) % 360.0)
    return d if d <= 180.0 else 360.0 - d


def _file_for(num):
    """Swiss Ephemeris file name / folder for a numbered asteroid."""
    if num in SPECIAL:
        return 'seas_18.se1', 'ephe/'
    folder = 'ast%d/' % (num // 1000)
    if num < 100000:
        return 'se%05ds.se1' % num, 'ephe/' + folder
    return 's%06ds.se1' % num, 'ephe/' + folder


def compute_asteroids(jd, lat, lon, ids, orb=3.0, aspects=False):
    """Positions of the requested asteroids plus contacts to the chart.

    The caller must have set the ephemeris path (app.py does this at
    import time and in each route).
    """
    # natal planets + angles
    planets = {}
    for name, pid in NATAL:
        try:
            planets[name] = swe.calc_ut(jd, pid)[0][0]
        except Exception:
            pass
    try:
        cusps, ascmc = swe.houses(jd, lat, lon, b'P')
        cusps = list(cusps[:12])
        planets['ASC'] = float(ascmc[0])
        planets['MC'] = float(ascmc[1])
    except Exception:
        cusps = [i * 30.0 for i in range(12)]

    out, missing = [], []
    for num in ids:
        pid = SPECIAL.get(num, swe.AST_OFFSET + num)
        try:
            xx = swe.calc_ut(jd, pid)[0]
        except Exception:
            # not installed yet - try to fetch it once, then retry
            got = ensure_file(num)
            if got:
                try:
                    xx = swe.calc_ut(jd, pid)[0]
                except Exception:
                    got = False
            if not got:
                hz = horizons_lonlat(num, jd)
                if hz is None:
                    fn, folder = _file_for(num)
                    missing.append({'id': num, 'file': fn, 'folder': folder})
                    continue
                xx = [hz[0], hz[1], None, None]
                src = 'horizons'
        src = locals().get('src', 'swisseph')
        deg = xx[0] % 360.0
        si = int(deg // 30)
        hits = []
        for pname, plon in planets.items():
            d = _sep(deg, plon)
            if d <= orb:
                hits.append({'planet': pname, 'aspect': 'შეერთება',
                             'sym': '☌', 'orb': round(d, 2)})
            elif aspects:
                for ang, an, asym in ASPECTS[1:]:
                    if abs(d - ang) <= orb:
                        hits.append({'planet': pname, 'aspect': an,
                                     'sym': asym, 'orb': round(abs(d - ang), 2)})
                        break
        hits.sort(key=lambda h: h['orb'])
        out.append({
            'id': num,
            'lon': round(deg, 4),
            'sign_idx': si,
            'sign_ka': SIGNS_KA[si],
            'deg_in_sign': round(deg % 30, 4),
            'element_ka': ELEMENT_KA[si % 4],
            'house': _house(deg, cusps),
            'speed': round(xx[3], 6) if len(xx) > 3 else 0.0,
            'retrograde': bool(len(xx) > 3 and xx[3] is not None and xx[3] < 0),
            'distance_au': round(xx[2], 6) if len(xx) > 2 and xx[2] is not None else None,
            'source': src,
            'contacts': hits,
        })
        src = 'swisseph'

    return {'asteroids': out, 'unavailable': missing,
            'planets': {k: round(v, 4) for k, v in planets.items()},
            'houses': [round(c, 4) for c in cusps], 'orb': orb}
 