# -*- coding: utf-8 -*-
"""
asteroids.py — real asteroid positions + conjunctions to the natal chart.

Replaces the old client-side page, whose positions were generated by a
pseudo-random hash of the asteroid number and were not astronomical.

Swiss Ephemeris computes each asteroid from its own data file:
  * Ceres, Pallas, Juno, Vesta      -> seas_18.se1   (already in ephe/)
  * Chiron, Pholus                  -> seas_18.se1   (already in ephe/)
  * every other numbered asteroid   -> se#####s.se1  (must be added)

Asteroids whose file is missing are reported in `unavailable` with the
exact filename needed, so nothing is ever invented.
"""

import math
import os
import urllib.request
import urllib.parse
import swisseph as swe

# Where the ephemeris lives (set by app.py; falls back to ./ephe)
EPHE_DIR = os.environ.get('SE_EPHE_PATH') or os.path.join(
    os.path.dirname(os.path.abspath(__file__)), 'ephe')

# Astrodienst mirrors, tried in order. The backend downloads an
# asteroid's file the first time it is requested and caches it in
# ephe/astN/, so no files have to be committed to the repo.
FILE_SOURCES = [
    'https://www.astro.com/ftp/swisseph/ephe/{folder}{file}',
    'https://www.astro.com/ftp/swisseph/ephe/{folder}{longfile}',
    'https://www.astro.com/ftp/swisseph/ephe/asteroids/{folder}{file}',
    'https://raw.githubusercontent.com/aloistr/swisseph/master/ephe/{folder}{file}',
]
_TRIED = set()
LAST_ERRORS = []          # why downloads failed (see /api/asteroids/diag)


def ensure_file(num):
    """Fetch this asteroid's Swiss Ephemeris file if we don't have it.

    Returns True when the file is present afterwards. Failures are
    remembered so a missing asteroid is only attempted once per process.
    """
    fn, folder = _file_for(num)
    if folder.startswith('ephe/'):
        folder = folder[5:]
    dest_dir = os.path.join(EPHE_DIR, folder) if folder else EPHE_DIR
    dest = os.path.join(dest_dir, fn)
    if os.path.exists(dest) and os.path.getsize(dest) > 1000:
        return True
    if num in _TRIED:
        return False
    _TRIED.add(num)
    try:
        os.makedirs(dest_dir, exist_ok=True)
    except Exception:
        return False
    longfn = fn.replace('s.se1', '.se1')      # full-precision variant
    for tpl in FILE_SOURCES:
        url = tpl.format(folder=folder, file=fn, longfile=longfn)
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'magnus-astro/1.0'})
            with urllib.request.urlopen(req, timeout=25) as r:
                data = r.read()
            if len(data) < 1000:          # not a real ephemeris file
                LAST_ERRORS.append('%s -> only %d bytes' % (url, len(data)))
                continue
            with open(dest, 'wb') as f:
                f.write(data)
            swe.set_ephe_path(EPHE_DIR)   # re-scan so the new file is seen
            return True
        except Exception as e:
            LAST_ERRORS.append('%s -> %s' % (url, e))
            continue
    return False


# ---------------------------------------------------------------
# FILE-FREE FALLBACK: NASA/JPL Horizons
# Astrodienst may refuse downloads from cloud IPs (the same problem
# app.py documents for the geocoders). Horizons serves positions over
# a plain HTTPS API and needs no local files at all.
# ---------------------------------------------------------------
HORIZONS = 'https://ssd.jpl.nasa.gov/api/horizons.api'
_HZ_CACHE = {}
_HZ_FILE = os.path.join(EPHE_DIR, 'horizons_cache.json')
try:
    import json as _json_hz
    with open(_HZ_FILE) as _f:
        for _k, _v in _json_hz.load(_f).items():
            _id, _jd = _k.split('|')
            _HZ_CACHE[(int(_id), float(_jd))] = tuple(_v)
except Exception:
    pass


def _save_hz_cache():
    try:
        import json as _j
        with open(_HZ_FILE, 'w') as f:
            _j.dump({'%d|%s' % k: list(v) for k, v in _HZ_CACHE.items()}, f)
    except Exception:
        pass


def horizons_many(nums, jd, workers=16):
    """Fetch several asteroids from Horizons in parallel."""
    from concurrent.futures import ThreadPoolExecutor
    todo = [n for n in nums if (n, round(jd, 5)) not in _HZ_CACHE]
    if todo:
        with ThreadPoolExecutor(max_workers=workers) as ex:
            list(ex.map(lambda n: horizons_lonlat(n, jd), todo))
        _save_hz_cache()
    return {n: _HZ_CACHE.get((n, round(jd, 5))) for n in nums}


def horizons_lonlat(num, jd):
    """Geocentric ecliptic longitude/latitude of asteroid `num` at jd."""
    key = (num, round(jd, 5))
    if key in _HZ_CACHE:
        return _HZ_CACHE[key]
    q = {
        'format': 'text',
        'COMMAND': "'%d;'" % num,        # ';' = small-body lookup by number
        'OBJ_DATA': 'NO',
        'MAKE_EPHEM': 'YES',
        'EPHEM_TYPE': 'OBSERVER',
        'CENTER': "'500@399'",           # geocentric
        'QUANTITIES': "'31'",            # observer ecliptic lon & lat
        'TLIST': '%.6f' % jd,
        'CSV_FORMAT': 'YES',
    }
    url = HORIZONS + '?' + urllib.parse.urlencode(q)
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'magnus-astro/1.0'})
        with urllib.request.urlopen(req, timeout=30) as r:
            txt = r.read().decode('utf-8', 'replace')
    except Exception as e:
        LAST_ERRORS.append('horizons %d -> %s' % (num, e))
        return None
    if '$$SOE' not in txt:
        LAST_ERRORS.append('horizons %d -> no ephemeris block' % num)
        return None
    body = txt.split('$$SOE', 1)[1].split('$$EOE', 1)[0].strip()
    line = body.splitlines()[0] if body.splitlines() else ''
    parts = [p.strip() for p in line.split(',')]
    nums = []
    for p in parts:
        try:
            nums.append(float(p))
        except ValueError:
            pass
    if len(nums) < 2:
        LAST_ERRORS.append('horizons %d -> unparsed: %s' % (num, line[:80]))
        return None
    lon, lat = nums[-2], nums[-1]
    _HZ_CACHE[key] = (lon % 360.0, lat)
    return _HZ_CACHE[key]

SIGNS_KA = ['ვერძი', 'კურო', 'ტყუპები', 'კირჩხიბი', 'ლომი', 'ქალწული',
            'სასწორი', 'მორიელი', 'მშვილდოსანი', 'თხის რქა',
            'მერწყული', 'თევზები']
ELEMENT_KA = ['ცეცხლი', 'მიწა', 'ჰაერი', 'წყალი']

# asteroids that live in the main-file set
SPECIAL = {1: swe.CERES, 2: swe.PALLAS, 3: swe.JUNO, 4: swe.VESTA,
           2060: swe.CHIRON, 5145: swe.PHOLUS}

# natal bodies asteroids are checked against
NATAL = [('მზე', swe.SUN), ('მთვარე', swe.MOON), ('მერკური', swe.MERCURY),
         ('ვენერა', swe.VENUS), ('მარსი', swe.MARS), ('იუპიტერი', swe.JUPITER),
         ('სატურნი', swe.SATURN), ('ურანი', swe.URANUS),
         ('ნეპტუნი', swe.NEPTUNE), ('პლუტონი', swe.PLUTO)]

ASPECTS = [(0.0, 'შეერთება', '☌'), (180.0, 'ოპოზიცია', '☍'),
           (120.0, 'ტრინი', '△'), (90.0, 'კვადრატი', '□'),
           (60.0, 'სექსტილი', '⚹')]


def _house(deg, cusps):
    for i in range(12):
        a, b = cusps[i], cusps[(i + 1) % 12]
        if a <= b:
            if a <= deg < b:
                return i + 1
        else:
            if deg >= a or deg < b:
                return i + 1
    return 1


def _sep(a, b):
    d = abs((a - b) % 360.0)
    return d if d <= 180.0 else 360.0 - d


def _file_for(num):
    """Swiss Ephemeris file name / folder for a numbered asteroid."""
    if num in SPECIAL:
        return 'seas_18.se1', 'ephe/'
    folder = 'ast%d/' % (num // 1000)
    if num < 100000:
        return 'se%05ds.se1' % num, 'ephe/' + folder
    return 's%06ds.se1' % num, 'ephe/' + folder



# ---------------------------------------------------------------
# LOCAL ELEMENT TABLES  (fast path, no network)
# For every asteroid we cannot read from a Swiss Ephemeris file we
# keep osculating orbital elements at 4-year epochs and propagate
# from the nearest one. Validated against Swiss Ephemeris for
# Ceres/Pallas/Juno/Vesta/Chiron/Pholus over 1900-2060: worst error
# 0.16 deg, typical 0.01 deg -- good enough for signs, houses and
# conjunctions. The tables are built once from JPL Horizons vectors
# and cached on disk, so later charts need no network at all.
# ---------------------------------------------------------------
GM_SUN = 0.0002959122082855911          # AU^3 / day^2
EPOCH_STEP_YEARS = 4
ELEM_FILE = os.path.join(EPHE_DIR, 'asteroid_elements.json')
_ELEMS = {}
try:
    import json as _json_el
    with open(ELEM_FILE) as _f:
        _ELEMS = {int(k): v for k, v in _json_el.load(_f).items()}
except Exception:
    _ELEMS = {}


def _save_elems():
    try:
        import json as _j
        with open(ELEM_FILE, 'w') as f:
            _j.dump({str(k): v for k, v in _ELEMS.items()}, f)
    except Exception:
        pass


def propagate_elements(el, jd):
    """Heliocentric ecliptic XYZ (AU) from one element set."""
    a, e, inc, Om, w, M0, epoch = el
    i, Om, w = math.radians(inc), math.radians(Om), math.radians(w)
    M = math.radians(M0) + math.sqrt(GM_SUN / a ** 3) * (jd - epoch)
    E = M
    for _ in range(40):
        E = E - (E - e * math.sin(E) - M) / (1 - e * math.cos(E))
    xp = a * (math.cos(E) - e)
    yp = a * math.sqrt(max(0.0, 1 - e * e)) * math.sin(E)
    cw, sw = math.cos(w), math.sin(w)
    cO, sO = math.cos(Om), math.sin(Om)
    ci, si = math.cos(i), math.sin(i)
    return ((cw * cO - sw * sO * ci) * xp + (-sw * cO - cw * sO * ci) * yp,
            (cw * sO + sw * cO * ci) * xp + (-sw * sO + cw * cO * ci) * yp,
            (sw * si) * xp + (cw * si) * yp)


def elements_lonlat(num, jd):
    """Geocentric ecliptic lon/lat from the local element table."""
    els = _ELEMS.get(num)
    if not els:
        return None
    el = min(els, key=lambda e: abs(e[6] - jd))
    if abs(el[6] - jd) > EPOCH_STEP_YEARS * 365.25 * 1.5:
        return None                      # outside the tabulated span
    x, y, z = propagate_elements(el, jd)
    try:
        sun = swe.calc_ut(jd, swe.SUN, swe.FLG_XYZ)[0]   # earth -> sun
    except Exception:
        return None
    gx, gy, gz = x + sun[0], y + sun[1], z + sun[2]
    r = math.sqrt(gx * gx + gy * gy + gz * gz)
    return ((math.degrees(math.atan2(gy, gx)) % 360.0),
            math.degrees(math.asin(gz / r)))


def horizons_vectors(num, jd):
    """Heliocentric state vector from Horizons -> osculating elements."""
    q = {'format': 'text', 'COMMAND': "'%d;'" % num, 'OBJ_DATA': 'NO',
         'MAKE_EPHEM': 'YES', 'EPHEM_TYPE': 'VECTORS',
         'CENTER': "'500@10'", 'VEC_TABLE': "'2'",
         'TLIST': '%.6f' % jd, 'CSV_FORMAT': 'YES', 'OUT_UNITS': "'AU-D'"}
    url = HORIZONS + '?' + urllib.parse.urlencode(q)
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'magnus-astro/1.0'})
        with urllib.request.urlopen(req, timeout=30) as r:
            txt = r.read().decode('utf-8', 'replace')
    except Exception as e:
        LAST_ERRORS.append('vectors %d -> %s' % (num, e))
        return None
    if '$$SOE' not in txt:
        return None
    line = txt.split('$$SOE', 1)[1].split('$$EOE', 1)[0].strip().splitlines()
    if not line:
        return None
    parts = []
    for p in line[0].split(','):
        try:
            parts.append(float(p.strip()))
        except ValueError:
            pass
    if len(parts) < 7:
        return None
    r_vec = parts[1:4]
    v_vec = parts[4:7]
    return _elements_from_state(r_vec, v_vec, jd)


def _elements_from_state(r, v, jd):
    R = math.sqrt(sum(c * c for c in r))
    V2 = sum(c * c for c in v)
    a = 1.0 / (2.0 / R - V2 / GM_SUN)
    h = [r[1]*v[2]-r[2]*v[1], r[2]*v[0]-r[0]*v[2], r[0]*v[1]-r[1]*v[0]]
    hm = math.sqrt(sum(c * c for c in h))
    rv = sum(r[j] * v[j] for j in range(3))
    ev = [(V2 - GM_SUN / R) * r[i] / GM_SUN - rv * v[i] / GM_SUN for i in range(3)]
    e = math.sqrt(sum(c * c for c in ev))
    inc = math.acos(max(-1, min(1, h[2] / hm)))
    n = [-h[1], h[0], 0.0]
    nm = math.hypot(n[0], n[1])
    Om = math.acos(max(-1, min(1, n[0] / nm))) if nm > 1e-12 else 0.0
    if n[1] < 0:
        Om = 2 * math.pi - Om
    if nm > 1e-12 and e > 1e-12:
        w = math.acos(max(-1, min(1, sum(n[j] * ev[j] for j in range(3)) / (nm * e))))
        if ev[2] < 0:
            w = 2 * math.pi - w
    else:
        w = 0.0
    nu = math.acos(max(-1, min(1, sum(ev[j] * r[j] for j in range(3)) / (e * R))))
    if rv < 0:
        nu = 2 * math.pi - nu
    E = 2 * math.atan2(math.tan(nu / 2) * math.sqrt(1 - e), math.sqrt(1 + e))
    M = E - e * math.sin(E)
    return [round(a, 9), round(e, 9), round(math.degrees(inc), 6),
            round(math.degrees(Om), 6), round(math.degrees(w), 6),
            round(math.degrees(M) % 360.0, 6), round(jd, 1)]


def build_elements(num, jd_from=2415020.5, jd_to=2469807.5, workers=8):
    """Fetch element sets at 4-year epochs (1900-2060) for one asteroid."""
    from concurrent.futures import ThreadPoolExecutor
    step = EPOCH_STEP_YEARS * 365.25
    epochs = []
    j = jd_from
    while j <= jd_to:
        epochs.append(j)
        j += step
    with ThreadPoolExecutor(max_workers=workers) as ex:
        got = list(ex.map(lambda e: horizons_vectors(num, e), epochs))
    els = [g for g in got if g]
    if len(els) < 5:
        return False
    _ELEMS[num] = els
    _save_elems()
    return True


_WARMING = set()


def warm_elements(nums):
    """Build missing element tables in a background thread.

    The current request is answered immediately from whatever is
    available; the next one for the same asteroid is instant and
    needs no network.
    """
    import threading
    todo = [n for n in nums
            if n not in _ELEMS and n not in _WARMING and n not in SPECIAL]
    if not todo:
        return
    _WARMING.update(todo)

    def work():
        for n in todo:
            try:
                build_elements(n)
            except Exception as e:
                LAST_ERRORS.append('warm %d -> %s' % (n, e))
            finally:
                _WARMING.discard(n)

    t = threading.Thread(target=work, daemon=True)
    t.start()

def compute_asteroids(jd, lat, lon, ids, orb=3.0, aspects=False):
    """Positions of the requested asteroids plus contacts to the chart.

    The caller must have set the ephemeris path (app.py does this at
    import time and in each route).
    """
    # natal planets + angles
    planets = {}
    for name, pid in NATAL:
        try:
            planets[name] = swe.calc_ut(jd, pid)[0][0]
        except Exception:
            pass
    try:
        cusps, ascmc = swe.houses(jd, lat, lon, b'P')
        cusps = list(cusps[:12])
        planets['ASC'] = float(ascmc[0])
        planets['MC'] = float(ascmc[1])
    except Exception:
        cusps = [i * 30.0 for i in range(12)]

    # which asteroids have no local file? resolve them together, in parallel
    need = []
    for num in ids:
        if num in SPECIAL:
            continue
        try:
            swe.calc_ut(jd, swe.AST_OFFSET + num)
        except Exception:
            need.append(num)
    # 1) anything already tabulated locally is free - no network
    still = [n for n in need if elements_lonlat(n, jd) is None]
    # build tables for those in the background so the NEXT chart is instant
    warm_elements(still)
    # 2) the rest: one Horizons position each, in parallel (first time only)
    if still:
        horizons_many(still, jd)

    out, missing = [], []
    for num in ids:
        pid = SPECIAL.get(num, swe.AST_OFFSET + num)
        try:
            xx = swe.calc_ut(jd, pid)[0]
        except Exception:
            # not installed yet - try to fetch it once, then retry
            got = ensure_file(num)
            if got:
                try:
                    xx = swe.calc_ut(jd, pid)[0]
                except Exception:
                    got = False
            if not got:
                hz = elements_lonlat(num, jd)
                src_tag = 'elements'
                if hz is None:
                    hz = _HZ_CACHE.get((num, round(jd, 5))) or horizons_lonlat(num, jd)
                    src_tag = 'horizons'
                if hz is None:
                    fn, folder = _file_for(num)
                    missing.append({'id': num, 'file': fn, 'folder': folder})
                    continue
                xx = [hz[0], hz[1], None, None]
                src = src_tag
        src = locals().get('src', 'swisseph')
        deg = xx[0] % 360.0
        si = int(deg // 30)
        hits = []
        for pname, plon in planets.items():
            d = _sep(deg, plon)
            if d <= orb:
                hits.append({'planet': pname, 'aspect': 'შეერთება',
                             'sym': '☌', 'orb': round(d, 2)})
            elif aspects:
                for ang, an, asym in ASPECTS[1:]:
                    if abs(d - ang) <= orb:
                        hits.append({'planet': pname, 'aspect': an,
                                     'sym': asym, 'orb': round(abs(d - ang), 2)})
                        break
        hits.sort(key=lambda h: h['orb'])
        out.append({
            'id': num,
            'lon': round(deg, 4),
            'sign_idx': si,
            'sign_ka': SIGNS_KA[si],
            'deg_in_sign': round(deg % 30, 4),
            'element_ka': ELEMENT_KA[si % 4],
            'house': _house(deg, cusps),
            'speed': (round(xx[3], 6) if len(xx) > 3 and xx[3] is not None else None),
            'retrograde': bool(len(xx) > 3 and xx[3] is not None and xx[3] < 0),
            'distance_au': round(xx[2], 6) if len(xx) > 2 and xx[2] is not None else None,
            'source': src,
            'contacts': hits,
        })
        src = 'swisseph'

    return {'asteroids': out, 'unavailable': missing,
            'planets': {k: round(v, 4) for k, v in planets.items()},
            'houses': [round(c, 4) for c in cusps], 'orb': orb}
